name: .NET

on:
  push:
    branches:
    - 'releases/**'
  pull_request:
    branches:
    - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env: 
        TESTAPIKEY: ${{secrets.TESTAPIKEY}}
    
    - name: Publish
      run: dotnet nuget push **/GetSongBpm.Net.*.nupkg --api-key $NUGETAPIKEY  --source https://api.nuget.org/v3/index.json
      env:
        NUGETAPIKEY: ${{secrets.NUGETAPIKEY}}
